replicas: 1

image:
  repository: microsoft/vsts-agent
  tag: ubuntu-16.04-docker-17.12.0-ce
  pullPolicy: Always

resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 0.1
    memory: 0.1
  disk: "30Gi"
  storageclass: "managed-standard"
